{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f006e489-ea24-4034-9964-d6e29f1878dd",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "=== MLB Live Monitor | 2026-04-10 14:49:15 ===\n",
      "只顯示正在進行中的比賽 | 第八局推播：ON\n",
      "============================================================================================================================================\n",
      "Pittsburgh Pirates 0 : 0 Chicago Cubs\n",
      "Top 3 | 0B1S 0Outs Bases ○ ○ ○\n",
      "P: Shota Imanaga ERA 3.75 | 36 Pitches\n",
      "B: Joey Bart AVG .167 | Next1 Billy Cook AVG .000 | Next2 Nick Yorke AVG .364\n",
      "--------------------------------------------------------------------------------------------------------------------------------------------\n"
     ]
    }
   ],
   "source": [
    "import time\n",
    "import requests\n",
    "from datetime import datetime\n",
    "from IPython.display import clear_output\n",
    "\n",
    "SCHEDULE_URL = \"https://statsapi.mlb.com/api/v1/schedule\"\n",
    "LIVE_URL = \"https://statsapi.mlb.com/api/v1.1/game/{gamePk}/feed/live\"\n",
    "\n",
    "ACTIVE_STATUSES = {\n",
    "    \"In Progress\",\n",
    "    \"Manager Challenge\",\n",
    "    \"Review\",\n",
    "}\n",
    "\n",
    "class MLBLiveMonitor:\n",
    "    def __init__(\n",
    "        self,\n",
    "        refresh_seconds: int = 10,\n",
    "        push_enabled: bool = True,\n",
    "        push_url: str = \"https://ntfy.sh/notiMLB26\",\n",
    "    ):\n",
    "        self.session = requests.Session()\n",
    "        self.refresh_seconds = refresh_seconds\n",
    "        self.push_enabled = push_enabled\n",
    "        self.push_url = push_url.strip()\n",
    "        self.eighth_inning_alerted = {}\n",
    "        self.running = False\n",
    "\n",
    "    def safe_get(self, d, *keys, default=\"\"):\n",
    "        cur = d\n",
    "        for k in keys:\n",
    "            if not isinstance(cur, dict):\n",
    "                return default\n",
    "            cur = cur.get(k)\n",
    "            if cur is None:\n",
    "                return default\n",
    "        return cur\n",
    "\n",
    "    def send_ntfy(self, title: str, message: str, priority: str = \"high\", tags=None):\n",
    "        if not self.push_enabled or not self.push_url:\n",
    "            return\n",
    "\n",
    "        headers = {\n",
    "            \"Title\": title,  # 請保持 ASCII，避免 header 編碼錯誤\n",
    "            \"Priority\": priority,\n",
    "            \"Content-Type\": \"text/plain; charset=utf-8\",\n",
    "        }\n",
    "        if tags:\n",
    "            headers[\"Tags\"] = \",\".join(tags)\n",
    "\n",
    "        r = requests.post(\n",
    "            self.push_url,\n",
    "            data=message.encode(\"utf-8\"),\n",
    "            headers=headers,\n",
    "            timeout=10\n",
    "        )\n",
    "        r.raise_for_status()\n",
    "\n",
    "    def get_today_games(self, date_str=None):\n",
    "        if date_str is None:\n",
    "            date_str = datetime.now().strftime(\"%Y-%m-%d\")\n",
    "\n",
    "        params = {\n",
    "            \"sportId\": 1,\n",
    "            \"date\": date_str\n",
    "        }\n",
    "\n",
    "        r = self.session.get(SCHEDULE_URL, params=params, timeout=15)\n",
    "        r.raise_for_status()\n",
    "        data = r.json()\n",
    "\n",
    "        games = []\n",
    "        for d in data.get(\"dates\", []):\n",
    "            for g in d.get(\"games\", []):\n",
    "                games.append({\n",
    "                    \"gamePk\": g[\"gamePk\"],\n",
    "                    \"away\": self.safe_get(g, \"teams\", \"away\", \"team\", \"name\", default=\"Away\"),\n",
    "                    \"home\": self.safe_get(g, \"teams\", \"home\", \"team\", \"name\", default=\"Home\"),\n",
    "                    \"status\": self.safe_get(g, \"status\", \"detailedState\", default=\"\"),\n",
    "                })\n",
    "        return games\n",
    "\n",
    "    def format_bases_compact(self, on_1b, on_2b, on_3b):\n",
    "        # 顯示順序：3B, 2B, 1B\n",
    "        return f\"{'●' if on_3b else '○'} {'●' if on_2b else '○'} {'●' if on_1b else '○'}\"\n",
    "\n",
    "    def format_bases_text(self, on_1b, on_2b, on_3b):\n",
    "        occupied = []\n",
    "        if on_3b:\n",
    "            occupied.append(\"3B\")\n",
    "        if on_2b:\n",
    "            occupied.append(\"2B\")\n",
    "        if on_1b:\n",
    "            occupied.append(\"1B\")\n",
    "\n",
    "        if len(occupied) == 3:\n",
    "            return \"滿壘\"\n",
    "        if not occupied:\n",
    "            return \"無人\"\n",
    "        return \" \".join(occupied)\n",
    "\n",
    "    def get_player_stat_avg(self, player_obj):\n",
    "        avg = self.safe_get(player_obj, \"seasonStats\", \"batting\", \"avg\", default=\"\")\n",
    "        if avg != \"\":\n",
    "            return avg\n",
    "\n",
    "        stat = self.safe_get(player_obj, \"stats\", \"batting\", \"avg\", default=\"\")\n",
    "        if stat != \"\":\n",
    "            return stat\n",
    "\n",
    "        summary = self.safe_get(player_obj, \"stats\", \"batting\", \"summary\", default=\"\")\n",
    "        return summary\n",
    "\n",
    "    def get_player_stat_era(self, player_obj):\n",
    "        era = self.safe_get(player_obj, \"seasonStats\", \"pitching\", \"era\", default=\"\")\n",
    "        if era != \"\":\n",
    "            return era\n",
    "\n",
    "        stat = self.safe_get(player_obj, \"stats\", \"pitching\", \"era\", default=\"\")\n",
    "        if stat != \"\":\n",
    "            return stat\n",
    "\n",
    "        summary = self.safe_get(player_obj, \"stats\", \"pitching\", \"summary\", default=\"\")\n",
    "        return summary\n",
    "\n",
    "    def get_pitch_count(self, player_obj):\n",
    "        candidates = [\n",
    "            self.safe_get(player_obj, \"stats\", \"pitching\", \"numberOfPitches\", default=\"\"),\n",
    "            self.safe_get(player_obj, \"stats\", \"pitching\", \"pitchesThrown\", default=\"\"),\n",
    "            self.safe_get(player_obj, \"seasonStats\", \"pitching\", \"numberOfPitches\", default=\"\"),\n",
    "        ]\n",
    "        for c in candidates:\n",
    "            if c != \"\":\n",
    "                return c\n",
    "        return \"\"\n",
    "\n",
    "    def get_live_snapshot(self, gamePk):\n",
    "        url = LIVE_URL.format(gamePk=gamePk)\n",
    "        r = self.session.get(url, timeout=15)\n",
    "        r.raise_for_status()\n",
    "        data = r.json()\n",
    "\n",
    "        game_data = data.get(\"gameData\", {})\n",
    "        live_data = data.get(\"liveData\", {})\n",
    "        linescore = live_data.get(\"linescore\", {})\n",
    "        plays = live_data.get(\"plays\", {})\n",
    "        boxscore = live_data.get(\"boxscore\", {})\n",
    "\n",
    "        away_name = self.safe_get(game_data, \"teams\", \"away\", \"name\", default=\"Away\")\n",
    "        home_name = self.safe_get(game_data, \"teams\", \"home\", \"name\", default=\"Home\")\n",
    "        status = self.safe_get(game_data, \"status\", \"detailedState\", default=\"\")\n",
    "\n",
    "        away_score = self.safe_get(linescore, \"teams\", \"away\", \"runs\", default=0)\n",
    "        home_score = self.safe_get(linescore, \"teams\", \"home\", \"runs\", default=0)\n",
    "\n",
    "        inning = linescore.get(\"currentInning\", \"\")\n",
    "        inning_state = linescore.get(\"inningState\", \"\")\n",
    "        outs = linescore.get(\"outs\", 0)\n",
    "\n",
    "        offense = linescore.get(\"offense\", {})\n",
    "        on_1b = \"first\" in offense\n",
    "        on_2b = \"second\" in offense\n",
    "        on_3b = \"third\" in offense\n",
    "\n",
    "        current_play = plays.get(\"currentPlay\", {})\n",
    "        batter_id = self.safe_get(current_play, \"matchup\", \"batter\", \"id\", default=None)\n",
    "        pitcher_id = self.safe_get(current_play, \"matchup\", \"pitcher\", \"id\", default=None)\n",
    "\n",
    "        batter_name = self.safe_get(current_play, \"matchup\", \"batter\", \"fullName\", default=\"\")\n",
    "        pitcher_name = self.safe_get(current_play, \"matchup\", \"pitcher\", \"fullName\", default=\"\")\n",
    "\n",
    "        balls = self.safe_get(current_play, \"count\", \"balls\", default=\"?\")\n",
    "        strikes = self.safe_get(current_play, \"count\", \"strikes\", default=\"?\")\n",
    "\n",
    "        all_players = {}\n",
    "        all_players.update(self.safe_get(boxscore, \"teams\", \"away\", \"players\", default={}) or {})\n",
    "        all_players.update(self.safe_get(boxscore, \"teams\", \"home\", \"players\", default={}) or {})\n",
    "\n",
    "        batter_avg = \"\"\n",
    "        pitcher_era = \"\"\n",
    "        pitcher_pitch_count = \"\"\n",
    "\n",
    "        if batter_id is not None:\n",
    "            batter_obj = all_players.get(f\"ID{batter_id}\", {})\n",
    "            batter_avg = self.get_player_stat_avg(batter_obj)\n",
    "\n",
    "        if pitcher_id is not None:\n",
    "            pitcher_obj = all_players.get(f\"ID{pitcher_id}\", {})\n",
    "            pitcher_era = self.get_player_stat_era(pitcher_obj)\n",
    "            pitcher_pitch_count = self.get_pitch_count(pitcher_obj)\n",
    "\n",
    "        offense_team_key = \"\"\n",
    "        if inning_state == \"Top\":\n",
    "            offense_team_key = \"away\"\n",
    "        elif inning_state == \"Bottom\":\n",
    "            offense_team_key = \"home\"\n",
    "\n",
    "        next_batters = []\n",
    "\n",
    "        if offense_team_key:\n",
    "            offense_team = self.safe_get(boxscore, \"teams\", offense_team_key, default={}) or {}\n",
    "            batting_order = offense_team.get(\"battingOrder\", []) or []\n",
    "            team_players = offense_team.get(\"players\", {}) or {}\n",
    "\n",
    "            current_index = None\n",
    "            if batter_id is not None:\n",
    "                batter_order_id = str(batter_id)\n",
    "                for idx, pid in enumerate(batting_order):\n",
    "                    if str(pid) == batter_order_id:\n",
    "                        current_index = idx\n",
    "                        break\n",
    "\n",
    "            if current_index is not None and len(batting_order) > 0:\n",
    "                for step in [1, 2]:\n",
    "                    next_idx = (current_index + step) % len(batting_order)\n",
    "                    next_pid = batting_order[next_idx]\n",
    "                    next_player_obj = team_players.get(f\"ID{next_pid}\", {})\n",
    "                    next_name = self.safe_get(next_player_obj, \"person\", \"fullName\", default=\"\")\n",
    "                    next_avg = self.get_player_stat_avg(next_player_obj)\n",
    "                    if next_name:\n",
    "                        next_batters.append({\n",
    "                            \"name\": next_name,\n",
    "                            \"avg\": next_avg\n",
    "                        })\n",
    "\n",
    "        return {\n",
    "            \"gamePk\": gamePk,\n",
    "            \"away\": away_name,\n",
    "            \"home\": home_name,\n",
    "            \"away_score\": away_score,\n",
    "            \"home_score\": home_score,\n",
    "            \"status\": status,\n",
    "            \"inning_state\": inning_state,\n",
    "            \"inning\": inning,\n",
    "            \"outs\": outs,\n",
    "            \"balls\": balls,\n",
    "            \"strikes\": strikes,\n",
    "            \"on_1b\": on_1b,\n",
    "            \"on_2b\": on_2b,\n",
    "            \"on_3b\": on_3b,\n",
    "            \"batter_name\": batter_name,\n",
    "            \"batter_avg\": batter_avg,\n",
    "            \"pitcher_name\": pitcher_name,\n",
    "            \"pitcher_era\": pitcher_era,\n",
    "            \"pitcher_pitch_count\": pitcher_pitch_count,\n",
    "            \"next_batters\": next_batters,\n",
    "        }\n",
    "\n",
    "    def check_eighth_inning_alert(self, s):\n",
    "        if not self.push_enabled or not self.push_url:\n",
    "            return\n",
    "\n",
    "        if s[\"status\"] not in ACTIVE_STATUSES:\n",
    "            return\n",
    "\n",
    "        if s[\"inning\"] != 8:\n",
    "            return\n",
    "\n",
    "        if s[\"inning_state\"] not in {\"Top\", \"Bottom\"}:\n",
    "            return\n",
    "\n",
    "        key = f\"{s['gamePk']}_8\"\n",
    "        if self.eighth_inning_alerted.get(key):\n",
    "            return\n",
    "\n",
    "        bases_text = self.format_bases_text(s[\"on_1b\"], s[\"on_2b\"], s[\"on_3b\"])\n",
    "        pitch_count_text = s[\"pitcher_pitch_count\"] if s[\"pitcher_pitch_count\"] != \"\" else \"?\"\n",
    "        next1 = s[\"next_batters\"][0] if len(s[\"next_batters\"]) >= 1 else {\"name\": \"?\", \"avg\": \"?\"}\n",
    "        next2 = s[\"next_batters\"][1] if len(s[\"next_batters\"]) >= 2 else {\"name\": \"?\", \"avg\": \"?\"}\n",
    "\n",
    "        title = f\"MLB 8th Inning Alert | {s['away']} @ {s['home']}\"\n",
    "        message = (\n",
    "            f\"{s['away']} {s['away_score']} : {s['home_score']} {s['home']}\\n\"\n",
    "            f\"{s['inning_state']} {s['inning']} | {s['balls']}B{s['strikes']}S | {s['outs']}Outs | 壘包 {bases_text}\\n\"\n",
    "            f\"P: {s['pitcher_name']} ERA {s['pitcher_era']} | {pitch_count_text} Pitches\\n\"\n",
    "            f\"B: {s['batter_name']} AVG {s['batter_avg']} | \"\n",
    "            f\"Next1 {next1['name']} AVG {next1['avg']} | \"\n",
    "            f\"Next2 {next2['name']} AVG {next2['avg']}\"\n",
    "        )\n",
    "\n",
    "        try:\n",
    "            self.send_ntfy(\n",
    "                title=title,\n",
    "                message=message,\n",
    "                priority=\"high\",\n",
    "                tags=[\"baseball\", \"bell\"]\n",
    "            )\n",
    "            self.eighth_inning_alerted[key] = True\n",
    "            print(f\"[PUSH] 已送出：{title}\")\n",
    "        except Exception as e:\n",
    "            print(f\"[PUSH] 失敗：{e}\")\n",
    "\n",
    "    def print_snapshot_four_lines(self, s):\n",
    "        bases_compact = self.format_bases_compact(s[\"on_1b\"], s[\"on_2b\"], s[\"on_3b\"])\n",
    "        pitch_count_text = s[\"pitcher_pitch_count\"] if s[\"pitcher_pitch_count\"] != \"\" else \"?\"\n",
    "        balls_text = s[\"balls\"] if s[\"balls\"] != \"\" else \"?\"\n",
    "        strikes_text = s[\"strikes\"] if s[\"strikes\"] != \"\" else \"?\"\n",
    "\n",
    "        line1 = f\"{s['away']} {s['away_score']} : {s['home_score']} {s['home']}\"\n",
    "        line2 = f\"{s['inning_state']} {s['inning']} | {balls_text}B {strikes_text}s {s['outs']}outs Bases {bases_compact}\"\n",
    "        line3 = f\"P: {s['pitcher_name']} ERA {s['pitcher_era']} | {pitch_count_text} Pitches\"\n",
    "\n",
    "        next1 = s[\"next_batters\"][0] if len(s[\"next_batters\"]) >= 1 else {\"name\": \"?\", \"avg\": \"?\"}\n",
    "        next2 = s[\"next_batters\"][1] if len(s[\"next_batters\"]) >= 2 else {\"name\": \"?\", \"avg\": \"?\"}\n",
    "        line4 = (\n",
    "            f\"B: {s['batter_name']} AVG {s['batter_avg']} | \"\n",
    "            f\"Next1 {next1['name']} AVG {next1['avg']} | \"\n",
    "            f\"Next2 {next2['name']} AVG {next2['avg']}\"\n",
    "        )\n",
    "\n",
    "        print(line1)\n",
    "        print(line2)\n",
    "        print(line3)\n",
    "        print(line4)\n",
    "        print(\"-\" * 140)\n",
    "\n",
    "    def render_header(self):\n",
    "        now_str = datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\")\n",
    "        print(f\"=== MLB Live Monitor | {now_str} ===\")\n",
    "        print(\"只顯示正在進行中的比賽 | 第八局推播：ON\" if self.push_enabled else \"只顯示正在進行中的比賽 | 第八局推播：OFF\")\n",
    "        print(\"=\" * 140)\n",
    "\n",
    "    def run(self):\n",
    "        self.running = True\n",
    "        while self.running:\n",
    "            try:\n",
    "                clear_output(wait=True)\n",
    "                self.render_header()\n",
    "\n",
    "                games = self.get_today_games()\n",
    "                games_to_show = [g for g in games if g[\"status\"] in ACTIVE_STATUSES]\n",
    "\n",
    "                if not games_to_show:\n",
    "                    print(\"目前沒有正在進行中的 MLB 比賽\")\n",
    "                    for _ in range(self.refresh_seconds):\n",
    "                        if not self.running:\n",
    "                            break\n",
    "                        time.sleep(1)\n",
    "                    continue\n",
    "\n",
    "                for g in games_to_show:\n",
    "                    if not self.running:\n",
    "                        break\n",
    "                    try:\n",
    "                        s = self.get_live_snapshot(g[\"gamePk\"])\n",
    "                        self.check_eighth_inning_alert(s)\n",
    "                        self.print_snapshot_four_lines(s)\n",
    "                    except Exception as e:\n",
    "                        print(f\"讀取單場失敗 {g['gamePk']} ({g['away']} @ {g['home']}): {e}\")\n",
    "                        print(\"-\" * 140)\n",
    "\n",
    "                for _ in range(self.refresh_seconds):\n",
    "                    if not self.running:\n",
    "                        break\n",
    "                    time.sleep(1)\n",
    "\n",
    "            except KeyboardInterrupt:\n",
    "                self.running = False\n",
    "                clear_output(wait=True)\n",
    "                print(\"已停止\")\n",
    "                break\n",
    "            except Exception as e:\n",
    "                clear_output(wait=True)\n",
    "                print(f\"主程式錯誤: {e}\")\n",
    "                time.sleep(2)\n",
    "\n",
    "    def stop(self):\n",
    "        self.running = False\n",
    "        try:\n",
    "            self.session.close()\n",
    "        except Exception:\n",
    "            pass\n",
    "        print(\"停止要求已送出\")\n",
    "\n",
    "\n",
    "monitor = MLBLiveMonitor(\n",
    "    refresh_seconds=10,\n",
    "    push_enabled=True,\n",
    "    push_url=\"https://ntfy.sh/notiMLB26\",\n",
    ")\n",
    "\n",
    "monitor.run()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f99e493c-2cec-4d26-865f-421fc452331b",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
